#!/usr/bin/env python3
"""Generate repo-local Codex skills from canonical AgentSpec Claude sources."""
from __future__ import annotations

import argparse
import re
import shutil
import sys
import tempfile
from pathlib import Path


SKILL_NAME = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
MAX_DESCRIPTION_LENGTH = 1024


class GenerationError(RuntimeError):
    """Raised when canonical sources cannot produce safe Codex adapters."""


def parse_frontmatter(text: str) -> dict[str, str]:
    """Parse the name and description fields from simple YAML frontmatter."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}

    try:
        closing = next(index for index, line in enumerate(lines[1:], 1) if line.strip() == "---")
    except StopIteration:
        return {}

    result: dict[str, str] = {}
    index = 1
    while index < closing:
        line = lines[index]
        match = re.match(r"^([A-Za-z0-9_-]+):(?:\s*(.*))?$", line)
        if not match:
            index += 1
            continue
        key, value = match.groups()
        value = value or ""
        if value in {"|", ">"}:
            block: list[str] = []
            index += 1
            while index < closing and (
                not lines[index].strip() or lines[index].startswith((" ", "\t"))
            ):
                block.append(lines[index].strip())
                index += 1
            separator = "\n" if value == "|" else " "
            result[key] = separator.join(block).strip()
            continue
        result[key] = value.strip().strip("\"'")
        index += 1
    return result


def _is_within(path: Path, root: Path) -> bool:
    """Return True when path is root itself or lies beneath it."""
    return path == root or root in path.parents


def _canonical_sources(
    repo_root: Path,
    command_sets: list[str] | None = None,
    allow_empty: bool = False,
) -> list[tuple[Path, bool]]:
    skill_root = repo_root / ".claude" / "skills"
    command_root = repo_root / ".claude" / "commands"
    agents_root = (repo_root / ".agents").resolve()

    skills: list[tuple[Path, bool]] = []
    for path in sorted(skill_root.glob("*/SKILL.md")):
        if _is_within(path.resolve(), agents_root):
            continue
        skills.append((path, False))

    if command_sets is None:
        command_paths = sorted(command_root.rglob("*.md"))
    else:
        command_paths = sorted(
            path
            for command_set in command_sets
            for path in (command_root / command_set).rglob("*.md")
        )
    commands = [(path, True) for path in command_paths if path.name != "README.md"]

    sources = skills + commands
    if not sources and not allow_empty:
        raise GenerationError("canonical source inventory is empty")
    return sources


def _source_metadata(path: Path) -> tuple[str, str]:
    metadata = parse_frontmatter(path.read_text(encoding="utf-8"))
    name = metadata.get("name", "").strip()
    description = metadata.get("description", "").strip()
    if not name:
        raise GenerationError(f"{path}: missing name")
    if not description:
        raise GenerationError(f"{path}: missing description")
    if not SKILL_NAME.fullmatch(name):
        raise GenerationError(f"{path}: invalid skill name {name!r}")
    return name, description


def _render_adapter(name: str, description: str, canonical_path: str) -> str:
    description = " ".join(description.split())
    if len(description) > MAX_DESCRIPTION_LENGTH:
        shortened = description[: MAX_DESCRIPTION_LENGTH - 3].rsplit(" ", 1)[0]
        description = f"{shortened}..."
    indented_description = "\n".join(f"  {line}" for line in description.splitlines())
    return f"""---
name: {name}
description: |
{indented_description}
---

# Generated AgentSpec adapter

Do not edit this file. The source of truth is `{canonical_path}`.

Before acting, open `{canonical_path}`; read it completely and follow it as the
authoritative workflow. Use Codex-native tools for equivalent Claude-specific
tool names. Preserve workspace paths under `.claude/`. If a required capability
has no Codex equivalent, identify that capability and stop at that boundary
instead of silently skipping it.
"""


def build_expected(
    repo_root: Path,
    command_sets: list[str] | None = None,
    allow_empty: bool = False,
) -> dict[str, str]:
    """Return relative adapter paths and their deterministic contents.

    ``allow_empty`` lets target-mode invocations (an explicit ``--root``)
    treat an empty source inventory as zero adapters instead of a hard
    failure — the target may not have synced any skills or commands yet.
    Repo-local invocations must keep failing closed, so callers that do not
    pass ``--root`` leave this at its default.
    """
    repo_root = repo_root.resolve()
    expected: dict[str, str] = {}
    owners: dict[str, Path] = {}
    for source, is_command in _canonical_sources(repo_root, command_sets, allow_empty):
        source = source.resolve()
        try:
            canonical_path = source.relative_to(repo_root).as_posix()
        except ValueError as error:
            raise GenerationError(f"source outside repository: {source}") from error
        if not canonical_path.startswith(".claude/"):
            raise GenerationError(f"source outside canonical collections: {source}")

        source_name, description = _source_metadata(source)
        output_name = f"agentspec-{source_name}" if is_command else source_name
        if not SKILL_NAME.fullmatch(output_name):
            raise GenerationError(f"{source}: invalid output name {output_name!r}")
        if output_name in owners:
            raise GenerationError(
                f"duplicate output name {output_name!r}: {owners[output_name]} and {source}"
            )
        owners[output_name] = source
        relative_output = f"{output_name}/SKILL.md"
        expected[relative_output] = _render_adapter(
            output_name, description, canonical_path
        )
    return dict(sorted(expected.items()))


def _actual_files(repo_root: Path) -> dict[str, str]:
    output_root = repo_root / ".agents" / "skills"
    if not output_root.exists():
        return {}
    return {
        path.relative_to(output_root).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(output_root.rglob("*"))
        if path.is_file()
    }


def find_drift(repo_root: Path, expected: dict[str, str]) -> list[str]:
    """Describe missing, changed, and unexpected generated files."""
    actual = _actual_files(repo_root)
    drift = [
        f"missing: {path}" for path in sorted(set(expected).difference(actual))
    ]
    drift.extend(
        f"changed: {path}"
        for path in sorted(set(expected).intersection(actual))
        if expected[path] != actual[path]
    )
    drift.extend(f"extra: {path}" for path in sorted(set(actual).difference(expected)))
    return drift


def preserved_entries(repo_root: Path, expected: dict[str, str]) -> list[str]:
    """Return top-level entries under the output root the generator does not own."""
    output_root = repo_root / ".agents" / "skills"
    if output_root.is_symlink() or not output_root.is_dir():
        return []
    generated = {Path(relative).parts[0] for relative in expected}
    return sorted(
        entry.name for entry in output_root.iterdir() if entry.name not in generated
    )


def write_adapters(
    repo_root: Path, expected: dict[str, str], preserve_unknown: bool = False
) -> None:
    """Replace the generated skills tree only after all output is validated."""
    agents_root = repo_root / ".agents"
    agents_root.mkdir(parents=True, exist_ok=True)
    output_root = agents_root / "skills"
    temporary = Path(tempfile.mkdtemp(prefix="skills.", dir=agents_root))
    try:
        if preserve_unknown:
            for name in preserved_entries(repo_root, expected):
                source = output_root / name
                destination = temporary / name
                if source.is_dir() and not source.is_symlink():
                    shutil.copytree(source, destination, symlinks=True)
                else:
                    shutil.copy2(source, destination, follow_symlinks=False)

        for relative_path, content in expected.items():
            destination = temporary / relative_path
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content, encoding="utf-8")

        if output_root.is_symlink() or output_root.is_file():
            output_root.unlink()
        elif output_root.exists():
            shutil.rmtree(output_root)
        temporary.replace(output_root)
    except Exception:
        if temporary.exists():
            shutil.rmtree(temporary)
        raise


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when committed Codex adapters differ from canonical sources",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="repository root to generate against (default: this repository)",
    )
    parser.add_argument(
        "--command-sets",
        default=None,
        help="comma-separated command directories to include (default: all)",
    )
    parser.add_argument(
        "--preserve-unknown",
        action="store_true",
        help="keep entries under .agents/skills/ the generator did not produce",
    )
    parser.add_argument(
        "--plan",
        action="store_true",
        help="report what would be generated without writing",
    )
    args = parser.parse_args(argv)
    allow_empty = args.root is not None
    repo_root = args.root if args.root is not None else Path(__file__).resolve().parent.parent
    repo_root = repo_root.resolve()
    command_sets = (
        [item for item in args.command_sets.split(",") if item]
        if args.command_sets is not None
        else None
    )

    try:
        expected = build_expected(repo_root, command_sets, allow_empty=allow_empty)
        if args.check:
            drift = find_drift(repo_root, expected)
            if drift:
                print("Codex adapters are out of date:", file=sys.stderr)
                for item in drift:
                    print(f"  {item}", file=sys.stderr)
                print(
                    "Run: python3 scripts/generate-codex-adapters.py",
                    file=sys.stderr,
                )
                return 1
            print(f"Codex adapters are current ({len(expected)} files).")
            return 0

        preserved = (
            preserved_entries(repo_root, expected) if args.preserve_unknown else []
        )
        if args.plan:
            print(f"would generate {len(expected)} adapters")
        else:
            write_adapters(repo_root, expected, args.preserve_unknown)
            print(f"generated {len(expected)} adapters")
        if preserved:
            print(f"preserved: {' '.join(preserved)}")
        return 0
    except GenerationError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
